### ISSUE TITLE
Dialogue box for apps larger than screen

### ISSUE THREAD

**Issue by anthrolisp** [kgilmer/Regolith-Desktop-Environment#13]
Dialogue box for apps are larger than screen. For example, the dialogue box for Gedit when you try to "save as" goes off the screen, and cannot see the bottom of the dialogue box.

**Comment by kgilmer** [comment]
Hi @anthrolisp this repo is no longer maintained.  I've moved the issue to the correct repo and will respond [there](https://github.com/regolith-linux/regolith-desktop/issues/22).
